<?php
$franchisees_map = [
  'AB - Edmonton - Kassian' => 0,

  'AL - Birmingham - Moore' => 477,
  'AL - Huntsville - Smith' => 561,
  'AL - Baldwin County - Dutton' => 471,

  'AR - Little Rock - Nobles' => 580,
  'AR - Springdale - Hudgeons' => 660,

  'AZ - Glendale - Rivera' => 474250,
  'AZ - Phoenix West - Harvin' => 684,
  'AZ - Phoenix East Valley - Abate' => 531,
	'AZ - Scottsdale - Lashley/Mroczek' => 651,

  'CA - Carlsbad - Parsons' => 486,
  'CA - Clovis - Dunn/Guenther' => 502,
 	'CA - Fremont - Chang' => 543,
  'CA - Fresno - Gragnani' => 544,
  'CA - Los Angeles - Takhmazyan' => 582,
  'CA - Marin County - Breur/Mendonca' => 553071,
  'CA - Orange County - Kube' => 622,
  'CA - Palo Alto - Marquez' => 625,
  'CA - Poway - Jabbour' => 632,
  'CA - San Jose - Silva' => 648,
  'CA - San Diego - Harris' => 646,
  'CA - San Diego North - Allen' => 645,
  'CA - San Francisco East - Rudow' => 647,
	'CA - Temecula - Vallejo' => 672,
  'CA - Thousand Oaks - Robinson' => 484001,

  'CO - Colorado Springs - Wetta' => 504,
  'CO - Denver North - Ragusa' => 612,
  'CO - Denver South - Hughes' => 519,
  'CO - Denver SE - Finch' => 474269,
  'CO - Denver - Brazzle' => 520,
	'CO - Fort Collins - Kaml' => 537,

  'CT - Danbury - Harrington/Claffey' => 515,
  'CT - East Hartford - Dabkowski' => 530,
  'CT - Fairfield - O\'Keefe' => 542336,
  'CT - Hartford - Dabkowski' => 530,
	'CT - Shoreline - Morra' => 653,

  'DE - Dover - Gonyo' => 524,

  'FL - Sebring - Perez/Hiraldo' => 477380,
  'FL - Brevard County - Sexton' => 480,
  'FL - Daytona - Dooley' => 517,
  'FL - Destin - Sabo' => 512867,
  'FL - Fort Lauderdale - Tommer/Cook' => 538,
  'FL - Fort Myers - Norkus/Cockreham' => 540,
	'FL - Gainesville - Roghaar' => 545,
	'FL - Hialeah - Gonzalez' => 557,
  'FL - Jacksonville - Roth' => 564,
  'FL - Lakeland - Lott' => 571,
  'FL - Naples - Pallipatte' => 601,
  'FL - Miami - Richards' => 594,
  'FL - Miami Beach - Garcia/Gomez' => 593,
  'FL - North Miami Beach - Sanford' => 614,
  'FL - Orlando - McKay' => 623,
  'FL - Palm Beach County - Reiss' => 624,
  'FL - Plant City - Lott' => 629,
  'FL - Plant City A - Lott' => 629,
  'FL - Plant City B - Lott' => 629,
  'FL - Plant City C - Lott' => 629,
  'FL - Port St. Lucie - Ackman' => 630,
  'FL - Sarasota - Bailey' => 649,
  'FL - St. Petersburg - Underwood' => 663,
  'FL - St. Petersburg A - Underwood' => 663,
  'FL - St. Petersburg B - Underwood' => 663,
  'FL - Tampa - CFPB' => 671,
  'FL - Tampa A - CFPB' => 671,
  'FL - Tampa B - CFPB' => 671,
	'FL - Winter Haven - Dennis' => 688,

  'GA - Atlanta - Panitch' => 467,
  'GA - Atlanta East - Castle/De Las Casas' => 466,
  'GA - Atlanta NE - Purgason' => 603,
  'GA - Atlanta West - Schmeidler' => 683,
  'GA - Augusta - McKinney' => 469,
  'GA - Columbus - Scott' => 508,
  'GA - Douglasville - Copenhaver/Hammer/Ison' => 523,
  'GA - Griffin - Moss' => 553,
	'GA - Jasper - Holcombe' => 565,
  'GA - Macon - Corn' => 587,
  'GA - Marietta - Ihm' => 590,
  'GA - Newton County - Chavez' => 542350,
  'GA - Newnan - Barron' => 608,
	'GA - Savannah - Nieves' => 650,

  'IA - Des Moines - Felker' => 521,

  'ID - Boise - Nelson' => 478,

  'IL - Arlington Heights - Paison/Fine' => 463,
  'IL - Brookfield - Smego' => 481,
  'IL - Chicago - Rothberg' => 499,
  'IL - Chicago SW - Ibraimi' => 498,
	'IL - Crystal Lake - Tamonis/Radcliffe' => 512,
  'IL - DuPage County - Conboy/Gignac' => 527,
  'IL - Lake County South - Djokic' => 570,
	'IL - Lake County North - Zivojinovic' => 613,
	'IL - Naperville - Cossyleon/Klimala' => 600,
  'IL - Rockford - Gummow/Dornbrook' => 641,
  'IL - Rockford - Chin' => 641,

  'IN - Indianapolis - Snyder' => 562,
	'IN - Indianapolis SW - Hunter' => 668,
  'IN - South Bend - Dorvilien/Scutt' => 656,

  'KS - Kansas City - Blundell/Helmer/Henry/Lampson' => 567,
  'KS - Kansas City - Henry' => 567,
	'KS - Topeka - McDowell' => 675,
  'KS - Wichita - Byrnes' => 686,

	'KY - Florence - Gordon' => 536,
  'KY - Lexington - Vaughn' => 578,
  'KY - North Lexington - Yaste' => 553073,
  'KY - Louisville - Martin' => 583,

	'LA - Acadiana - Embroli' => 458,
  'LA - Baton Rouge - Breaux' => 473,
  'LA - Covington - McAndrew/Henry' => 477364,

  'MA - Boston South - Tereshko' => 657,
  'MA - SE Boston - Astley/Astley/Cunning' => 500221,
  'MA - Springfield - Monroe' => 511980,
  'MA - Chelmsford - MarcAurele' => 495,
  'MA - Worcester - Belisle' => 542339,

  'MD - Anne Arundel - Bates' => 461,
	'MD - Calvert - Morgan' => 483,
  'MD - Prince Georges County - Stevens/Tompkins' => 633,
  'MD - Washington DC - Metro' => 682,
  'MD - Baltimore - Corp' => 472,
  'MD - Bel Air - Moses' => 475,
  'MD - Howard County - Perkins' => 489,
  'MD - Upper Marlboro - Westbrooks' => 591,

  'MI - Ann Arbor - Davis' => 460,
  'MI - Canton - Whitchurch' => 484,
  'MI - Detroit - Hagerman' => 522,
	'MI - Flint - Hawley' => 456,
  'MI - Oakland County - Ryan/Lipa' => 620,
  'MI - Grand Rapids - Cusack' => 548,
	'MI - Grosse Pointe - Hagerman' => 554,
  'MI - Kalamazoo - Jacob' => 566,
  'MI - Kalamazoo A - Jacob' => 566,
  'MI - Kalamazoo B - Jacob' => 566,
  'MI - Lansing - Burkle/Willbrandt' => 572,
  'MI - Macomb County - Saad' => 586,

  'MN - Eden Prairie - Sedlak' => 533,
  'MN - Minneapolis - Christiansen' => 596,
  'MN - Minneapolis North - Knoebel' => 615,
  'MN - Minnetonka - Thomas' => 597,
  'MN - St. Paul - Knospe' => 662,
  'MN - Shoreview - Spille' => 654,

  'MO - St Louis - Provo' => 661,
  'MO - Columbia - Dullard' => 505,
  'MO - Kansas City North - Henning' => 568,
  'MO - Lees Summit - Rodick' => 575,

  'MS - Hattiesburg - Wallace' => 512876,
  'MS - Jackson - Carter' => 563,

  'NC - Asheville - Smith' => 465,
  'NC - Charlotte - Harper' => 493,
  'NC - Charlotte East - Brown' => 529,
  'NC - Fayetteville - Houston' => 542347,
  'NC - Greensboro - Auman' => 550,
	'NC - Greenville - Kumar' => 551,
  'NC - Raleigh - Roper' => 636,
  'NC - Statesville Mooresville - McCormick' => 664,
  'NC - Thomasville - Shone' => 674,
  'NC - Wilmington - Moss' => 687,

	'ND - Fargo - Fronk/Biss' => 535,

  'NE - OmahaLincoln - Hughes' => 579,
  'NE - OmahaLincoln B - Hughes' => 579,

  'NH - Manchester - Broom' => 589,
  'NH - Portsmouth - Batchelder' => 484010,

  'NJ - Atlantic City - Hubner' => 468,
  'NJ - Cherry Hill - Spaulding' => 496,
  'NJ - Somerset County - Giordano' => 655,
  'NJ - East Brunswick - Meyler' => 528,
  'NJ - Freehold - Phillips' => 553075,
  'NJ - North - Garcia' => 616,
  'NJ - North - Corp' => 616,
  'NJ - North B - Corp' => 616,
  'NJ - Trenton - Changpertitum/Liao' => 676,

  'NV - Henderson - Epstein' => 556,
  'NV - Las Vegas - Guy' => 573,
  'NV - Reno - Severson' => 637,
  'NV - Summerlin - Bethune' => 665,

  'NY - Long Island - Nickliancos' => 581,
  'NY - MT. Kisco - Jozefiak' => 598,
  'NY - Westchester - Corp' => 685,

  'OH - Cincinnati - Rogers' => 500,
  'OH - Cleveland - Loughridge' => 501,
  'OH - Central Columbus - Donovan/Olson' => 511975,
  'OH - Columbus - Arpin/Arthur' => 507,
  'OH - Columbus - Delaware' => 507,
  'OH - Columbus-Delaware - Tietjen' => 507,
  'OH - Columbus North - Thomas' => 610,
  'OH - Lebanon - Harper' => 484016,

  'OK - Jenks - Foster' => 474429,
  'OK - Mustang - Wagner' => 542344,
  'OK - Oklahoma City - Dufek' => 621,
  'OK - Tulsa - Culbertson' => 678,

  'OR - Bend - Parker' => 476,
  'OR - Portland - Lombardo' => 631,
  'OR - Happy Valley - Lane' => 555,

  'PA - Allentown - Gall' => 459,
  'PA - Bucks County - Losco' => 482,
  'PA - Carlisle - Wickard/Kassel' => 485,
	'PA - Levittown - Patel' => 577,
  'PA - South Chester - Lawrie' => 497,
  'PA - South Chester A - Lawrie' => 497,
  'PA - South Chester B - Lawrie' => 497,
  'PA - Philadelphia - Ort' => 626,
  'PA - Central PA - Potosky' => 491,
  'PA - Pittsburgh West - Charles' => 627,

  'RI - Providence - DeNunzio' => 634,

  'SC - Charleston - Simmons' => 492,
	'SC - Columbia - Sullivan' => 506,
  'SC - Greenville - Truelove' => 552,
  'SC - Hilton Head - Brown' => 558,
  'SC - Myrtle Beach - Smith' => 599,
  'SC - Rock Hill - Hernandez' => 640,
  'SC - Spartanburg - Wells' => 658,

  'TN - Chattanooga - Collins' => 474436,
  'TN - Knoxville - Secore' => 569,
  'TN - Nashville - Lombardi' => 602,
  'TN - Nashville B - Lombardi' => 602,
  'TN - Tri - Cities - Delmar' => 542342,

  'TX - Arlington - Rohlfs' => 500236,
  'TX - Austin Junk - Lampson' => 470,
  'TX - Austin Move North - Hiegel' => 470,
  'TX - Central Austin - Harris/Lombardi' => 470,
  'TX - Baytown - Amos/Davis' => 542334,
  'TX - Beaumont - Danna' => 474,
  'TX - College Station - Rosas' => 503,
	'TX - Conroe - Quintanilha' => 510,
	'TX - Copperfield - Witkowsky' => 511,
  'TX - Dallas Central - Cook' => 487,
  'TX - Dallas Carrollton - Leffel' => 513,
	'TX - Dallas Garland - Quintanilla' => 514,
  'TX - Dallas Southwest - Rohlfs' => 477369,
  'TX - Midlothian - Matthews' => 512871,
	'TX - North Dallas - Rosales/Arredondo' => 611,
	'TX - North Dallas - Arredondo/Rosales' => 611,
  'TX - Denton - Ablitt' => 518,
  'TX - Eldridge - Mance' => 534,
  'TX - Fort Worth - Gaither/Bush' => 541,
  'TX - NE Fort Worth - Reyes/Carron' => 604,
  'TX - SW Ft. Worth - Winegarden' => 666,
  'TX - Keller - Collins' => 512873,
  'TX - New Braunfels  - Kalambayi' => 607,
  'TX - New Braunfels - Kalambayi' => 607,
  'TX - Houston - Wood' => 560,
  'TX - Houston NE - Wright' => 605,
  'TX - Houston Central - Smith' => 488,
  'TX - Houston South - Winders' => 559,
  'TX - Houston SW - Luedecke' => 667,
  'TX - League City - Wilkins' => 574,
  'TX - Lubbock - Ritter' => 584,
  'TX - McKinney - O\'Hanna' => 592,
  'TX - Plano - Bhakta' => 628,
  'TX - Rockwall - Lee' => 642,
  'TX - Round Rock Move - Tayong' => 477373,
  'TX - San Antonio - Smith' => 644,
  'TX - San Antonio West - Lauderdale/Czarobski/Wilson/Lane' => 618,
  'TX - NE San Antonio - Good' => 606,
  'TX - NW San Antonio - Joiner' => 618,
  'TX - SW San Antonio - Belyeu' => 669,
  'TX - Waco - Mills' => 681,
  'TX - The Woodlands - Mejia' => 673,

  'UT - Draper - Moss' => 526,
  'UT - Provo - Hendrickson' => 635,
  'UT - Salt Lake City SW - Bice' => 643,
  'UT - South Jordan - Starace' => 483977,

  'VA - Arlington - Craig' => 464,
  'VA - Virginia NW - Berkebile' => 680,
  'VA - Charlottesville - Lokey' => 494,
  'VA - Fredericksburg - Bovain' => 542,
  'VA - Leesburg - Rowles' => 576,
  'VA - Newport News - Perkins' => 609,
  'VA - Reston - Shure' => 483987,
  'VA - Richmond - Patel/Amin' => 639,
  'VA - Richmond East - Chapman' => 532,
  'VA - Virginia Beach - Atkinson' => 679,

  'WA - Gig Harbor - Beisley' => 547,
  'WA - Gig Harbor A - Beisley' => 547,
  'WA - Gig Harbor B - Beisley' => 547,
  'WA - Lynnwood - Thirlwall' => 585,
  'WA - Renton - Davis' => 638,
  'WA - Seattle Central - Olason' => 652,
  'WA - Spokane - Paramore' => 659,
  'WA - Tacoma - Christian/Evans' => 670,

	'WI - Appleton - Holt' => 462,
  'WI - Green Bay - Goetz/Klapa' => 549,
  'WI - Kenosha - Finerty' => 477361,
	'WI - Madison - Larsen' => 588,
  'WI - Milwaukee - Coenen' => 595,
	'WI - Oak Creek - Gunderson' => 619,
  'WI - Germantown - Wetzel' => 546,
];